use wasm_encoder::{BlockType, Function, Instruction as W, ValType};

use super::descriptor::{trap_if, trap_on_stack};
use super::memory::memarg;

const PAGE_SIZE: i64 = 65_536;

pub(super) fn emit_drop(free_index: u32) -> Function {
    let mut body = Function::new([(5, ValType::I64), (5, ValType::I32)]);
    body.instruction(&W::LocalGet(0));
    body.instruction(&W::I32Load(memarg(28)));
    body.instruction(&W::I32Const(1));
    body.instruction(&W::I32Eq);
    trap_on_stack(&mut body);
    validate_header(&mut body);
    validate_shape(&mut body);
    validate_data(&mut body);
    body.instruction(&W::LocalGet(6));
    body.instruction(&W::I32Const(1));
    body.instruction(&W::I32And);
    body.instruction(&W::I32Eqz);
    body.instruction(&W::If(BlockType::Empty));
    body.instruction(&W::LocalGet(8));
    body.instruction(&W::I32Eqz);
    trap_on_stack(&mut body);
    body.instruction(&W::Return);
    body.instruction(&W::End);
    body.instruction(&W::LocalGet(2));
    body.instruction(&W::I64Eqz);
    body.instruction(&W::If(BlockType::Empty));
    body.instruction(&W::Else);
    body.instruction(&W::LocalGet(8));
    body.instruction(&W::Call(free_index));
    body.instruction(&W::End);
    body.instruction(&W::LocalGet(0));
    body.instruction(&W::I32Const(0));
    body.instruction(&W::I32Store(memarg(24)));
    body.instruction(&W::LocalGet(0));
    body.instruction(&W::LocalGet(6));
    body.instruction(&W::I32Const(!1));
    body.instruction(&W::I32And);
    body.instruction(&W::I32Store(memarg(4)));
    body.instruction(&W::LocalGet(0));
    body.instruction(&W::I32Const(1));
    body.instruction(&W::I32Store(memarg(28)));
    body.instruction(&W::End);
    body
}

fn validate_header(body: &mut Function) {
    body.instruction(&W::LocalGet(0));
    body.instruction(&W::I32Eqz);
    trap_on_stack(body);
    body.instruction(&W::LocalGet(0));
    body.instruction(&W::I32Const(7));
    body.instruction(&W::I32And);
    body.instruction(&W::I32Eqz);
    body.instruction(&W::I32Eqz);
    trap_on_stack(body);
    body.instruction(&W::MemorySize(0));
    body.instruction(&W::I64ExtendI32U);
    body.instruction(&W::I64Const(PAGE_SIZE));
    body.instruction(&W::I64Mul);
    body.instruction(&W::LocalSet(1));
    body.instruction(&W::LocalGet(0));
    body.instruction(&W::I64ExtendI32U);
    body.instruction(&W::I64Const(40));
    body.instruction(&W::I64Add);
    body.instruction(&W::LocalGet(1));
    trap_if(body, W::I64GtU);
    field_eq(body, 0, 2);
    field_eq(body, 16, 0);
    field_eq(body, 28, 0);
    body.instruction(&W::LocalGet(0));
    body.instruction(&W::I32Load(memarg(4)));
    body.instruction(&W::LocalTee(6));
    body.instruction(&W::I32Const(!3));
    body.instruction(&W::I32And);
    body.instruction(&W::I32Eqz);
    body.instruction(&W::I32Eqz);
    trap_on_stack(body);
}

fn validate_shape(body: &mut Function) {
    body.instruction(&W::LocalGet(0));
    body.instruction(&W::I32Load(memarg(20)));
    body.instruction(&W::LocalTee(7));
    body.instruction(&W::I32Const(8));
    trap_if(body, W::I32GtU);
    body.instruction(&W::LocalGet(0));
    body.instruction(&W::I64ExtendI32U);
    body.instruction(&W::I64Const(40));
    body.instruction(&W::LocalGet(7));
    body.instruction(&W::I64ExtendI32U);
    body.instruction(&W::I64Const(16));
    body.instruction(&W::I64Mul);
    body.instruction(&W::I64Add);
    body.instruction(&W::I64Add);
    body.instruction(&W::LocalGet(1));
    trap_if(body, W::I64GtU);
    body.instruction(&W::LocalGet(0));
    body.instruction(&W::I32Load(memarg(8)));
    body.instruction(&W::LocalSet(8));
    body.instruction(&W::LocalGet(0));
    body.instruction(&W::I32Load(memarg(12)));
    body.instruction(&W::LocalSet(9));
    validate_tag_size(body);
    body.instruction(&W::I64Const(1));
    body.instruction(&W::LocalSet(2));
    body.instruction(&W::I64Const(0));
    body.instruction(&W::LocalSet(3));
    body.instruction(&W::Block(BlockType::Empty));
    body.instruction(&W::Loop(BlockType::Empty));
    body.instruction(&W::LocalGet(3));
    body.instruction(&W::LocalGet(7));
    body.instruction(&W::I64ExtendI32U);
    body.instruction(&W::I64GeU);
    body.instruction(&W::BrIf(1));
    body.instruction(&W::LocalGet(0));
    body.instruction(&W::LocalGet(3));
    body.instruction(&W::I64Const(16));
    body.instruction(&W::I64Mul);
    body.instruction(&W::I32WrapI64);
    body.instruction(&W::I32Add);
    body.instruction(&W::I64Load(memarg(40)));
    body.instruction(&W::LocalTee(4));
    body.instruction(&W::I64Const(1_i64 << 31));
    trap_if(body, W::I64GtU);
    body.instruction(&W::LocalGet(2));
    body.instruction(&W::LocalSet(5));
    body.instruction(&W::LocalGet(2));
    body.instruction(&W::LocalGet(4));
    body.instruction(&W::I64Mul);
    body.instruction(&W::LocalSet(2));
    body.instruction(&W::LocalGet(4));
    body.instruction(&W::I64Eqz);
    body.instruction(&W::If(BlockType::Empty));
    body.instruction(&W::Else);
    body.instruction(&W::LocalGet(2));
    body.instruction(&W::LocalGet(4));
    body.instruction(&W::I64DivU);
    body.instruction(&W::LocalGet(5));
    trap_if(body, W::I64Ne);
    body.instruction(&W::End);
    body.instruction(&W::LocalGet(3));
    body.instruction(&W::I64Const(1));
    body.instruction(&W::I64Add);
    body.instruction(&W::LocalSet(3));
    body.instruction(&W::Br(0));
    body.instruction(&W::End);
    body.instruction(&W::End);
    body.instruction(&W::LocalGet(0));
    body.instruction(&W::I64Load(memarg(32)));
    body.instruction(&W::LocalGet(2));
    trap_if(body, W::I64Ne);
}

fn validate_data(body: &mut Function) {
    body.instruction(&W::LocalGet(0));
    body.instruction(&W::I32Load(memarg(24)));
    body.instruction(&W::LocalSet(8));
    body.instruction(&W::LocalGet(2));
    body.instruction(&W::I64Eqz);
    body.instruction(&W::If(BlockType::Empty));
    body.instruction(&W::Else);
    body.instruction(&W::LocalGet(8));
    body.instruction(&W::I32Eqz);
    trap_on_stack(body);
    body.instruction(&W::LocalGet(8));
    body.instruction(&W::I64ExtendI32U);
    body.instruction(&W::LocalGet(2));
    body.instruction(&W::LocalGet(9));
    body.instruction(&W::I64ExtendI32U);
    body.instruction(&W::I64Mul);
    body.instruction(&W::I64Add);
    body.instruction(&W::LocalGet(1));
    trap_if(body, W::I64GtU);
    body.instruction(&W::End);
}

fn field_eq(body: &mut Function, offset: u64, expected: i32) {
    body.instruction(&W::LocalGet(0));
    body.instruction(&W::I32Load(memarg(offset)));
    body.instruction(&W::I32Const(expected));
    trap_if(body, W::I32Ne);
}

fn validate_tag_size(body: &mut Function) {
    body.instruction(&W::LocalGet(8));
    body.instruction(&W::I32Const(1));
    body.instruction(&W::I32GeU);
    body.instruction(&W::LocalGet(8));
    body.instruction(&W::I32Const(11));
    body.instruction(&W::I32LeU);
    body.instruction(&W::I32And);
    body.instruction(&W::I32Eqz);
    trap_on_stack(body);
    body.instruction(&W::LocalGet(8));
    body.instruction(&W::I32Const(2));
    body.instruction(&W::I32LeU);
    body.instruction(&W::LocalGet(8));
    body.instruction(&W::I32Const(11));
    body.instruction(&W::I32Eq);
    body.instruction(&W::I32Or);
    body.instruction(&W::If(BlockType::Result(ValType::I32)));
    body.instruction(&W::I32Const(1));
    body.instruction(&W::Else);
    body.instruction(&W::LocalGet(8));
    body.instruction(&W::I32Const(4));
    body.instruction(&W::I32LeU);
    body.instruction(&W::If(BlockType::Result(ValType::I32)));
    body.instruction(&W::I32Const(2));
    body.instruction(&W::Else);
    body.instruction(&W::LocalGet(8));
    body.instruction(&W::I32Const(6));
    body.instruction(&W::I32LeU);
    body.instruction(&W::LocalGet(8));
    body.instruction(&W::I32Const(9));
    body.instruction(&W::I32Eq);
    body.instruction(&W::I32Or);
    body.instruction(&W::If(BlockType::Result(ValType::I32)));
    body.instruction(&W::I32Const(4));
    body.instruction(&W::Else);
    body.instruction(&W::I32Const(8));
    body.instruction(&W::End);
    body.instruction(&W::End);
    body.instruction(&W::End);
    body.instruction(&W::LocalGet(9));
    trap_if(body, W::I32Ne);
}
